apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-12-13T17:55:31Z
  generation: 1
  labels:
    run: react
  name: react
  namespace: default
  resourceVersion: "628"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/react
  uid: cfca96f5-e02e-11e7-8cb2-42010a80027f
spec:
  replicas: 1
  selector:
    matchLabels:
      run: react
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: react
    spec:
      containers:
      - image: gcr.io/np-sc1-distributionservices/react:v1
        imagePullPolicy: IfNotPresent
        name: react
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-12-13T17:55:31Z
    lastUpdateTime: 2017-12-13T17:55:31Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-12-13T18:12:50Z
  labels:
    run: react
  name: react
  namespace: default
  resourceVersion: "2176"
  selfLink: /api/v1/namespaces/default/services/react
  uid: 3b162c4f-e031-11e7-8cb2-42010a80027f
spec:
  clusterIP: 10.55.252.113
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: react
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 151.140.0.0/16
    - 165.130.0.0/16
    - 207.11.0.0/17
    - 50.207.27.182/32
    - 98.6.11.8/29
status:
  loadBalancer:
    ingress:
- ip: 35.226.221.3